### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/jsdoc-region-tag#10]
while running `npm run docs` on [nodejs-spanner](https://github.com/googleapis/nodejs-spanner) and [nodejs-bigtable](https://github.com/googleapis/nodejs-bigtable) it gives following error:
Let me know if I am missing anything, because it's working perfectly on CI.
```ts
const key = tag.replace('region_tag:', '').trim()
                        ^
TypeError: Cannot read property 'replace' of undefined
    at Parser.newDoclet (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc-region-tag\index.js:77:25)
    at Parser.emit (events.js:214:15)
    at addDoclet (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\handlers.js:157:16)
    at newSymbolDoclet (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\handlers.js:321:5)
    at Parser.<anonymous> (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\handlers.js:365:13)
    at Parser.emit (events.js:209:13)
    at Visitor.visitNode (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\visitor.js:849:20)
    at Visitor.visit (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\visitor.js:759:21)
    at Walker.recurse (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\walker.js:694:42)
    at Parser._walkAst (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\parser.js:305:22)
    at Parser._parseSourceCode (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\parser.js:296:22)      
    at Parser.parse (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\lib\jsdoc\src\parser.js:202:22)
    at Object.module.exports.cli.parseFiles (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\cli.js:365:46)
    at module.exports.cli.main (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\cli.js:234:18)
    at Object.module.exports.cli.runCommand (F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\cli.js:186:9)
    at F:\Google\nodejs\nodejs-spanner\node_modules\jsdoc\jsdoc.js:93:9
```
**Possible Solution:**
add below line before doing any operation on `tag`:
```ts
if (!tag) continue;
 ```
https://github.com/googleapis/jsdoc-region-tag/blob/4e5daeb718ea2b3d9be1c80a2ffc8082a96effa5/index.js#L75

I am happy to create PR if above solution is correct.

**Comment by bcoe** [comment]
@laljikanjareeya would happily accept a patch, I would be curious to know what content in the `jsdoc` string of spanner is creating this issue however? It sounds like it might potentially be a badly formed `jsdoc` string.

**Comment by laljikanjareeya** [comment]
Here is the examples where `jsdocs` is not proper:

- spanner_query_dataamples/crud.js
- startamples/quickstart.js
- spanner_create_databases/schema.js
- spanner_insert_datamples/crud.js
- spanner_read_datasamples/crud.js
- spanner_update_datamples/crud.js

actually in spanner we are still using `<caption></caption>` syntax.
